[package]
name = "influxdb_line_protocol"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["rlib", "staticlib"]

[features]
ffi = ["libc"]

[dependencies] # In alphabetical order
bytes = "1.4"
libc = { version = "0.2", optional = true }
nom = { version = "7", default-features = false, features = ["std"] }
smallvec = { version = "1.10.0", features = ["union"] }
snafu = "0.7"
observability_deps = { path = "../observability_deps" }
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies] # In alphabetical order
test_helpers = { path = "../test_helpers" }
